AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  API:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: BPDTS-Test-API
      ProtocolType: HTTP
      Target:
        !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${HandlerArn}/invocations
          - { HandlerArn: !GetAtt Handler.Arn }
      CredentialsArn: !GetAtt APIRole.Arn
  APIRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource: "*"
        -
          PolicyName: InvokeLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt Handler.Arn

  Handler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bpdts-test
      Runtime: nodejs12.x
      CodeUri: src/
      Handler: index.handler
      Policies:
        -
          Statement:
            - 
              Effect: Allow
              Action: 
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:GetLogEvents
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
